server {

    listen 443 ssl;

    ssl_certificate        /etc/certs/device-cert.pem;
    ssl_certificate_key    "store:pkcs11:token=RPi%20OTP%20key;id=%01;type=private";

    ssl_protocols TLSv1.3;
    
    location / {
        root   /var/www/localhost/html;
        index  index.html index.htm;
    }
}
