[Service]
User=www
Group=www
SupplementaryGroups=vcio
AmbientCapabilities=CAP_NET_BIND_SERVICE
LogsDirectory=nginx
RuntimeDirectory=nginx
Type=exec
ExecStart=
ExecStart=/usr/sbin/nginx -g "daemon off;"
ExecStartPre=
ExecStartPre=/bin/sh -c 'while [ ! -s /etc/certs/rpi-device-cert.pem ]; do sleep 1; done'
RestartSec=3
Restart=on-failure
