# Per-device suricatta (hawkBit) settings:

# hawkBit server URL
SURICATTA_URL=https://embetrix.works/hawkbit

# hawkBit tenant
SURICATTA_TENANT=default

# Controller/device id reported to hawkBit
# Leave unset to default to the device hostname
#SURICATTA_ID=

# hawkBit gateway security token
#SURICATTA_GATEWAY_TOKEN=
