# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have a packages directory, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "raspberrypi-secure"
BBFILE_PATTERN_raspberrypi-secure := "^${LAYERDIR}/"
BBFILE_PRIORITY_raspberrypi-secure = "9"
LAYERSERIES_COMPAT_raspberrypi-secure = "wrynose"
LAYERDEPENDS_raspberrypi-secure = "core openembedded-layer raspberrypi integrity security selinux avb tpm-layer swupdate"

# Set a variable to get to the top of the meta-layer location
RPI_SECURE_BASE := '${LAYERDIR}'
