# USBGuard rules configuration file

# Allow the RPi4 VL805 PCIe-USB root hubs (all USB ports go through these)
allow 1d6b:0002 with-interface 09:00:00 via-port match-all
allow 1d6b:0003 with-interface 09:00:00 via-port match-all

# Allow specific USB devices (adapt to your needs)

# Kingston Technology DataTraveler
allow 0951:1666

# Reject everything else
reject
