# USBGuard rules configuration file

# Allow specific USB devices (adapt to your needs):

## RPi4 VL805 PCIe-USB root hubs (all USB ports go through these)
allow 2109:3431
allow 2109:2817

# Kingston Technology DataTraveler
allow 0951:1666

# OmniKey AG CardMan 5022
allow 076b:5022

# Reject everything else
reject
