# USBGuard rules configuration file

# Allow specific USB devices (adapt to your needs):

## RPi4 VL805 PCIe-USB root hubs (all USB ports go through these)
allow 1d6b:0002
allow 1d6b:0003

## Kingston Technology DataTraveler
allow 0951:1666

# Reject everything else
reject
