RuleFile=/etc/usbguard/rules.conf
AuditBackend=LinuxAudit
IPCAllowedUsers=root
IPCAllowedGroups=
ImplicitPolicyTarget=block
PresentDevicePolicy=apply-policy
PresentControllerPolicy=keep
InsertedDevicePolicy=apply-policy
AuthorizedDefault=none
RestoreControllerDeviceState=false
DeviceManagerBackend=uevent
