# SPDX-License-Identifier: MIT
# Copyright (C) 2026 Embetrix Embedded Systems Solutions <ayoub.zaki@embetrix.com>

require conf/distro/poky.conf

DISTRO = "rpi-secure"
DISTRO_NAME = "rpi-secure"

# Distro Features
DISTRO_FEATURES:append = " systemd polkit ima integrity security selinux tpm2"

INIT_MANAGER = "systemd"

# Pull Raspberry Pi security machine settings transparently from the distro.
require conf/machine/include/rpi-secure.inc

# Set persistent Logs
VOLATILE_LOG_DIR = "no"

# Selinux configuration
PREFERRED_PROVIDER_virtual/refpolicy = "refpolicy-mls"
IMAGE_CLASSES += "selinux-image selinux-image-order"
DEFAULT_ENFORCING = "${@bb.utils.contains('RPI_SECURITY_PROFILE', 'prod', 'permissive', 'permissive', d)}"
#DEFAULT_ENFORCING = "${@bb.utils.contains('RPI_SECURITY_PROFILE', 'prod', 'enforcing', 'permissive', d)}"

# IMA/EVM Rootfs Signing
INHERIT += "ima-evm-rootfs"
IMAGE_CLASSES += "ima-evm-rootfs-extra"

# AVB/DM-Verity configuration
IMAGE_CLASSES += "avb-verity"
IMAGE_FSTYPES += " ${ROOTFS_TYPE}.avbverity.gz"
AVB_ROOT_HASH_SIGN = "1"
