##########################################################################
# Distro conf file
##########################################################################
DISTRO = "rpi-secure"
DISTRO_NAME = "rpi secure"
require conf/distro/poky.conf

# Enforce baseline compiler/linker hardening flags for Rust.
require conf/distro/include/rust_security_flags.inc

# Enable security-oriented features globally for this distro.
DISTRO_FEATURES:append = " ima integrity security"

# Disable development-friendly insecure behavior.
EXTRA_IMAGE_FEATURES:remove = "debug-tweaks"

# Enable Kernel module signing
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# WARNING: Debug keys to replace with production keys before deployment
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
MODSIGN_KEY_DIR  = "${INTEGRITY_BASE}/data/debug-keys"
MODSIGN_PRIVKEY ?= "${MODSIGN_KEY_DIR}/privkey_modsign.pem"
MODSIGN_X509    ?= "${MODSIGN_KEY_DIR}/x509_modsign.crt"

# Enable IMA/EVM rootfs signing
INHERIT += "ima-evm-rootfs"
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# WARNING: Debug keys to replace with production keys before deployment
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
IMA_EVM_KEY_DIR = "${INTEGRITY_BASE}/data/debug-keys"
IMA_EVM_PRIVKEY ?= "${IMA_EVM_KEY_DIR}/privkey_ima.pem"
IMA_EVM_X509 ?= "${IMA_EVM_KEY_DIR}/x509_ima.der"

# Pull Raspberry Pi security machine settings transparently from the distro.
require conf/machine/include/rpi-secure.inc
