# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 Embetrix Embedded Systems Solutions <ayoub.zaki@embetrix.com>

require conf/distro/poky.conf

DISTRO = "rpi-secure"
DISTRO_NAME = "rpi-secure"

# Distro Features
DISTRO_FEATURES:append = " systemd ima integrity security tpm2"

INIT_MANAGER = "systemd"

# Pull Raspberry Pi security machine settings transparently from the distro.
require conf/machine/include/rpi-secure.inc

# Set persistent Logs
VOLATILE_LOG_DIR = "no"
