[Unit]
ConditionFileNotEmpty=/etc/certs/rpi-device-cert.pem

[Service]
User=www
Group=www
SupplementaryGroups=rpifwcrypto
AmbientCapabilities=CAP_NET_BIND_SERVICE
LogsDirectory=nginx
RuntimeDirectory=nginx
Type=exec
ExecStart=
ExecStart=/usr/sbin/nginx -g "daemon off;"
RestartSec=3
Restart=on-failure
