#!/bin/sh
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright 2026 Embetrix Embedded Systems Solutions <ayoub.zaki@embetrix.com>
#
# Generate all signing keys for meta-raspberrypi-secure and print the
# corresponding BitBake variables to set in local.conf or kas header
#
# Usage: genkey-helper.sh [KEY_DIR]
#   KEY_DIR  directory to store generated keys (default: /tmp/rpi-secure-keys)

set -e

KEY_DIR="${1:-/tmp/rpi-secure-keys}"
KEY_DIR="$(cd "$(dirname "$KEY_DIR")" 2>/dev/null && pwd)/$(basename "$KEY_DIR")" || KEY_DIR="$(readlink -f "$KEY_DIR")"
TOP_LAYER_DIR="$(cd "$(dirname "$0")/.." 2>/dev/null && pwd)"

CN="rpi-secure"
ORG="Embetrix"
DAYS=3650

mkdir -p "$KEY_DIR"

echo "Generating signing keys in: $KEY_DIR:"

# Secure-boot signing private key (RSA 2048) 
SECBOOT_KEY="$KEY_DIR/privkey_secure-bootsign.pem"
echo "  Generating secure-boot signing key (RSA-2048) ..."
openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:2048 \
    -out "$SECBOOT_KEY" 2>/dev/null
chmod 600 "$SECBOOT_KEY"

# IMA/EVM private key (EC prime256v1)
IMA_PRIVKEY="$KEY_DIR/privkey_ima.pem"
echo "  Generating IMA/EVM private key ..."
openssl genpkey -algorithm EC -pkeyopt ec_paramgen_curve:prime256v1 \
    -out "$IMA_PRIVKEY" 2>/dev/null
chmod 600 "$IMA_PRIVKEY"

# IMA/EVM x509 certificate (DER)
IMA_X509="$KEY_DIR/x509_ima.der"
echo "  Generating IMA/EVM x509 certificate (DER) ..."
openssl req -new -x509 -sha256 -days "$DAYS" -batch \
    -subj "/CN=$CN-imaevm dev/O=$ORG" \
    -addext "basicConstraints=critical,CA:FALSE" \
    -addext "keyUsage=digitalSignature" \
    -addext "extendedKeyUsage=critical,codeSigning" \
    -addext "subjectKeyIdentifier=hash" \
    -key "$IMA_PRIVKEY" -outform DER -out "$IMA_X509" 2>/dev/null
chmod 644 "$IMA_X509"

# Kernel module signing private key (EC prime256v1) 
MODSIGN_PRIVKEY="$KEY_DIR/privkey_modsign.pem"
echo "  Generating kernel module signing private key ..."
openssl genpkey -algorithm EC -pkeyopt ec_paramgen_curve:prime256v1 \
    -out "$MODSIGN_PRIVKEY" 2>/dev/null
chmod 600 "$MODSIGN_PRIVKEY"

# Kernel module signing x509 certificate (PEM)
MODSIGN_X509="$KEY_DIR/x509_modsign.pem"
echo "  Generating kernel module signing x509 certificate (PEM) ..."
openssl req -new -x509 -sha256 -days "$DAYS" -batch \
    -subj "/CN=$CN-modsign dev/O=$ORG" \
    -addext "basicConstraints=critical,CA:FALSE" \
    -addext "keyUsage=digitalSignature" \
    -addext "extendedKeyUsage=critical,codeSigning" \
    -addext "subjectKeyIdentifier=hash" \
    -key "$MODSIGN_PRIVKEY" -outform PEM -out "$MODSIGN_X509" 2>/dev/null
chmod 644 "$MODSIGN_X509"

# SSH CA key pair (ed25519)
SSH_CA_KEY="$KEY_DIR/ssh_ca_key"
SSH_CA_PUB="$KEY_DIR/ssh_ca_key.pub"
KAS_FRAGMENT="$TOP_LAYER_DIR/kas-signing-keys.yml"
echo "  Generating SSH CA key pair (ed25519) ..."
# ssh-keygen requires a valid passwd entry:
# create a temporary one in CI for the current uid if missing
getent passwd "$(id -u)" >/dev/null 2>&1 || echo "build:x:$(id -u):$(id -g)::/tmp:/sbin/nologin" >> /etc/passwd
HOME=/tmp ssh-keygen -t ed25519 -f "$SSH_CA_KEY" -N "" -C "$ORG SSH CA" -q
chmod 600 "$SSH_CA_KEY"
chmod 644 "$SSH_CA_PUB"

# Auto-generate a ready-to-use kas fragment with resolved key paths.
cat > "$KAS_FRAGMENT" <<EOF
# Generated by $(basename "$0") on $(date)
header:
    version: 11

local_conf_header:
    signing_keys: |
        RPI_SIGNING_KEYS_DIR     = "$KEY_DIR"
        RPI_SECURE_BOOT_SIGN_KEY = "$SECBOOT_KEY"
        IMA_EVM_PRIVKEY          = "$IMA_PRIVKEY"
        IMA_EVM_X509             = "$IMA_X509"
        MODSIGN_PRIVKEY          = "$MODSIGN_PRIVKEY"
        MODSIGN_X509             = "$MODSIGN_X509"
        OPENSSH_CA_PUBKEY        = "$SSH_CA_PUB"
EOF
chmod 600 "$KAS_FRAGMENT"


echo
echo "All keys generated successfully."
echo
echo "Add the following to your local.conf (or kas header):"
echo "#######################################################"
cat <<EOF
RPI_SIGNING_KEYS_DIR     = "$KEY_DIR"
RPI_SECURE_BOOT_SIGN_KEY = "$SECBOOT_KEY"
IMA_EVM_PRIVKEY          = "$IMA_PRIVKEY"
IMA_EVM_X509             = "$IMA_X509"
MODSIGN_PRIVKEY          = "$MODSIGN_PRIVKEY"
MODSIGN_X509             = "$MODSIGN_X509"
OPENSSH_CA_PUBKEY        = "$SSH_CA_PUB"
EOF
echo "#######################################################"
echo
echo "Generated kas fragment: $(basename "$KAS_FRAGMENT")"
echo "Use it directly in your build:"
echo "  kas build kas-rpi-secure.yml:$(basename "$KAS_FRAGMENT")"
echo
echo "SSH CA private key (keep secret): $SSH_CA_KEY"
echo
echo "To sign the client keys with the CA:"
echo "  ssh-keygen -s $SSH_CA_KEY -I user-rpi  -n rpi  -V +1w $SSH_CLIENT_PUB"
echo "  ssh-keygen -s $SSH_CA_KEY -I user-root -n root -V +1d $SSH_ROOT_PUB"
echo
echo "To connect:"
echo "  ssh -i $SSH_CLIENT_KEY rpi@<device-ip>"
echo "  ssh -i $SSH_ROOT_KEY root@<device-ip>"
echo
echo "NOTICE: These file-based keys are not suitable for high security requirements :"
echo "For production, store private keys in a Hardware Security Module (HSM)"
echo "or TPM and use PKCS#11 URIs instead of file based keys"
echo